name: RegenWD
version: 1.0.0
api-version: 1.15
author: nivcoo
main: fr.nivcoo.regenwd.RegenWD
commands:
  regenwd:
    description: regenWD
permissions:
  regenwd.commands:
    default: op
    description: /regenwd